[package]
name = "macros"
version = "0.0.0"
edition = "2021"

[lib]
proc-macro = true

[dependencies]
quote = "1.0"
anyhow = "1.0"
proc-macro2 = "1.0"

syn = { version = "1.0", features = [ "full", "fold", "printing", "parsing" ] }
