cargo-features = ["per-package-target"]

[package]
name = "deltavfs-host32"
version = "0.0.0"
edition = "2021"
forced-target = "i686-pc-windows-msvc"

[lib]
crate-type = ["cdylib"]

[dependencies]
deltavfs-host = { version = "0.0.0", path = "../deltavfs-host" }
